export const CATEGORIES = [
  {
    id: 'job',
    label: '취업',
    desc: '지원서, 면접, 준비 과정',
    defaultTitle: '취업 준비 중',
    icon: 'Briefcase',
    accent: '#8B5CF6',
    accentBg: '#F5F3FF',
    gradientFrom: '#EDE9FE',
    gradientTo: '#DDD6FE',
  },
  {
    id: 'study',
    label: '공부',
    desc: '오늘의 배움, 독서, 연구',
    defaultTitle: '오늘의 공부',
    icon: 'BookOpen',
    accent: '#667EEA',
    accentBg: '#F0F4FF',
    gradientFrom: '#DDE6FF',
    gradientTo: '#C2D1FF',
  },
  {
    id: 'workout',
    label: '운동 / 건강',
    desc: '운동, 컨디션, 몸 상태',
    defaultTitle: '건강 관리',
    icon: 'Dumbbell',
    accent: '#10b981',
    accentBg: '#f0fdf4',
    gradientFrom: '#d1fae5',
    gradientTo: '#a7f3d0',
  },
  {
    id: 'hobby',
    label: '취미',
    desc: '좋아하는 것, 만드는 즐거움',
    defaultTitle: '취미 생활',
    icon: 'Palette',
    accent: '#f59e0b',
    accentBg: '#fffbeb',
    gradientFrom: '#fde68a',
    gradientTo: '#fcd34d',
  },
  {
    id: 'cert',
    label: '자격증',
    desc: '시험 일정, 목표 점수, 진행률',
    defaultTitle: '자격증 취득',
    icon: 'Award',
    accent: '#f43f5e',
    accentBg: '#fff1f2',
    gradientFrom: '#fecdd3',
    gradientTo: '#fda4af',
  },
];

export const MOOD_STICKERS = [
  { code: '포근', label: '포근', color: 'bg-point-100/75 text-point-600 border-point-300' },
  { code: '멍함', label: '멍함', color: 'bg-slate-100/85 text-slate-500 border-slate-300' },
  { code: '반짝', label: '반짝', color: 'bg-amber-100/70 text-amber-600 border-amber-300' },
  { code: '잔잔', label: '잔잔', color: 'bg-blue-50/90 text-blue-500 border-blue-300' },
  { code: '버팀', label: '버팀', color: 'bg-green-50/90 text-green-600 border-green-300' },
  { code: '두근', label: '두근', color: 'bg-rose-50/90 text-rose-500 border-rose-300' },
];
